---
# tasks file for radiorabe.common.core

- name: radiorabe.common.core -- Print core info
  ansible.builtin.debug:
    msg: 
    - "radiorabe_core_hostname: {{ radiorabe_core_hostname }}"
    - "radiorabe_core_int_hostname: {{ radiorabe_core_int_hostname }}"
    - "radiorabe_core_realm: {{ radiorabe_core_realm }}"
    - "radiorabe_core_admin_name: {{ radiorabe_core_admin_name }}"
    - "radiorabe_core_admin_mail: {{ radiorabe_core_admin_mail }}"
  tags:
    - always
