namespace: radiorabe
name: common
version: 0.0.0
readme: README.md
authors:
  - Lucas Bickel <@hairmare>
description: RaBe Ansible Roles and Playbooks for use with Foreman
license_file: LICENSE
tags:
  - radiorabe
  - foreman
  - common
dependencies: {}
repository: https://github.com/radiorabe/ansible-collection-common
documentation: https://github.com/radiorabe/ansible-collection-common/blob/main/README.md
homepage: hhttps://github.com/radiorabe/ansible-collection-common
issues: https://github.com/radiorabe/ansible-collection-common/issues
