---
# tasks file for radiorabe.common.selinux_modules

- name: Download selinux modules
  ansible.builtin.include_role:
    name: radiorabe.common.download_file
  vars:
    download_file_url: "{{ item.url }}"
    download_file_destination: "{{ selinux_modules_download_file_destination }}"
    download_file_mode: "{{ selinux_modules_download_file_mode }}"
    download_file_locally: "{{ selinux_modules_download_file_locally }}"
  with_items: "{{ selinux_modules_download_file_urls }}"
  when: item.state is not defined or item.state == 'enabled'

- name: Install selinux modules
  ansible.builtin.include_role:
    name: redhat.rhel_system_roles.selinux
  vars:
    selinux_modules:
      - path: "./{{ item.url | basename }}"
        state: "{{ item.state |  default('enabled') }}"
  with_items: "{{ selinux_modules_download_file_urls }}"