---
exclude_paths:
  - .ansible/
  - .github/
  - venv/
  - molecule/

write_list:
  - all

warn_list:
  - experimental

# Profile can be: min, basic, moderate, safety, shared, production
profile: production
