---
- name: Converge
  hosts: all
  tasks:
    - name: Apply core role (required dependency)
      ansible.builtin.include_role:
        name: radiorabe.common.core

    - name: Apply base role
      ansible.builtin.include_role:
        name: radiorabe.common.base
