---
galaxy_info:
  author: RaBe IT-Reaktion
  description: Required configuration for [RaBe backup](https://github.com/radiorabe/backup)
  issue_tracker_url: https://github.com/radiorabe/ansible-collection-common/issues
  license: AGPL-3.0-only
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - all
    - name: Fedora
      version:
        - all
  galaxy_tags:
    - radiorabe
    - foreman
    - common
    - system
    - backup
dependencies: []