---
dependency:
  name: galaxy

driver:
  name: podman

platforms:
  - name: local-user-el9
    image: docker.io/almalinux:9
    command: sleep infinity
    pre_build_image: true

provisioner:
  name: ansible
  env:
    ANSIBLE_PIPELINING: "True"
    ANSIBLE_FORCE_COLOR: "True"

verifier:
  name: ansible
