---
# tasks file for radiorabe.common.git

- name: 'RaBe Common : git_clone : Clone git repository locally'
  ansible.builtin.git: '{{ item }}'
  with_items: '{{ radiorabe_git_clone }}'
  delegate_to: 127.0.0.1
  when: radiorabe_git_local_clone == true

- name: 'RaBe Common : git_clone : Copy files to remote'
  ansible.builtin.copy: 
    src: '{{ item.dest }}/'
    dest: '{{ radiorabe_git_clone_remote_dest }}/'
  with_items: '{{ radiorabe_git_clone }}'
  when: radiorabe_git_local_clone == true

- name: 'RaBe Common : git_clone : Clone git repository on remote'
  ansible.builtin.git: '{{ item }}'
  with_items: '{{ radiorabe_git_clone }}'
  when: radiorabe_git_local_clone == false