---
# tasks file for radiorabe.common.git

- name: "RaBe Common : git_clone : Clone git repository {{ 'locally' if radiorabe_git_local_clone else 'on remote host' }}"
  ansible.builtin.git: "{{ item }}" # noqa: latest args
  with_items: "{{ radiorabe_git_clone }}"
  delegate_to: "{{ '127.0.0.1' if radiorabe_git_local_clone else omit }}"

- name: "RaBe Common : git_clone : Copy files to remote"
  ansible.builtin.copy:
    src: "{{ item.dest }}/"
    dest: "{{ radiorabe_git_clone_remote_dest }}/"
    owner: "{{ radiorabe_git_clone_remote_owner | default(omit) }}"
    group: "{{ radiorabe_git_clone_remote_group | default(omit) }}"
  with_items: "{{ radiorabe_git_clone }}"
  when: radiorabe_git_local_clone
