---
# tasks file for download_file
- name: Download file {{ 'locally' if download_file_locally }}
  ansible.builtin.get_url:
    url: "{{ download_file_url }}"
    dest: "{{ download_file_destination }}"
    mode: "{{ download_file_mode }}"
  delegate_to: "{{ '127.0.0.1' if download_file_locally else omit }}"
