---
# tasks file for download_file
- name: Download file
  ansible.builtin.get_url:
    url: "{{ download_file_url }}"
    dest: "{{ download_file_destination }}"
  when: download_file_locally == false

# tasks file for download_file
- name: Download file locally
  ansible.builtin.get_url:
    url: "{{ download_file_url }}"
    dest: "{{ download_file_destination }}"
  delegate_to: 127.0.0.1
  when: download_file_locally == true
  
