---
# tasks file for radiorabe.common.local_user

- name: "Ensure group {{ local_user_groupname }}"
  become: true
  ansible.builtin.group:
    name: "{{ local_user_groupname }}"
    state: present
  when: local_user_groupname | length > 0

- name: "Ensure user {{ local_user_username }}"
  become: true
  ansible.builtin.user:
    name: "{{ local_user_username }}"
    groups: "{{ local_user_additional_groups if local_user_additional_groups | length > 0 else omit }}"
    group: "{{ local_user_groupname if local_user_groupname | length > 0 else omit }}"
    home: "{{ local_user_home_directory if local_user_home_directory | length > 0 else omit }}"
    shell: "{{ local_user_shell if local_user_shell | length > 0 else omit }}"
    system: "{{ local_user_system }}"
    create_home: "{{ local_user_create_home }}"
    state: present
