---
- name: Converge
  hosts: all
  tasks:
    - name: Apply selinux_modules role with a test module URL
      ansible.builtin.include_role:
        name: radiorabe.common.selinux_modules
      vars:
        selinux_modules_download_file_urls:
          - url: "https://rabe.ch/wp-content/uploads/2016/07/favicon.ico"
            state: enabled
        selinux_modules_download_file_destination: /tmp/
        selinux_modules_download_file_mode: "0600"
        selinux_modules_download_file_locally: false

    - name: Apply selinux_modules role with disabled module (should not download)
      ansible.builtin.include_role:
        name: radiorabe.common.selinux_modules
      vars:
        selinux_modules_download_file_urls:
          - url: "https://rabe.ch/wp-content/uploads/2016/07/favicon.ico"
            state: disabled
        selinux_modules_download_file_destination: /tmp/
        selinux_modules_download_file_locally: false
