---
- name: Converge
  hosts: all
  tasks:
    - name: Download file to remote host
      ansible.builtin.include_role:
        name: radiorabe.common.download_file
      vars:
        download_file_url: "https://raw.githubusercontent.com/radiorabe/ansible-collection-common/main/galaxy.yml"
        download_file_destination: /tmp/test_remote_download.yml
        download_file_mode: "0644"
        download_file_locally: false

    - name: Download file with restricted permissions
      ansible.builtin.include_role:
        name: radiorabe.common.download_file
      vars:
        download_file_url: "https://raw.githubusercontent.com/radiorabe/ansible-collection-common/main/galaxy.yml"
        download_file_destination: /tmp/test_restricted_download.yml
        download_file_mode: "0600"
        download_file_locally: false
