name: Lint and Test

on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow:
    uses: radiorabe/actions/.github/workflows/test-ansible-collection.yaml@479996126a091287dc3fd349786f6f8a6dd1b23c # v0.42.0
  github-actions:
    permissions:
      contents: read
      security-events: write # so zizmor can publish results to the Security tab
    uses: radiorabe/actions/.github/workflows/test-github-actions.yaml@479996126a091287dc3fd349786f6f8a6dd1b23c # v0.42.0
  molecule:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        role:
          - base
          - core
          - download_file
          - files
          - git_clone
          - local_user
          - packages
          - rabe_backup
          - selinux_modules
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install Molecule and dependencies
        run: pip install -r requirements.txt

      - name: Run Molecule tests for role ${{ matrix.role }}
        run: molecule test
        working-directory: roles/${{ matrix.role }}
